baseurl = "https://francetalentpass.com"
DefaultContentLanguage = "zh-CN"
DefaultContentLanguageInSubdir = true
title = "France Talent Passport - 从申请到法国生活全流程指南"
# Using theme as git submodule
theme = "beautifulhugo"
# Or when using theme as hugo module
# theme = "github.com/halogenica/beautifulhugo"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[Services]
  [Services.Disqus]
    shortname = "francetalentpass"
  [Services.googleAnalytics]
    id = "G-0124XPB5RC"

[Params]
  homeTitle = "法国人才护照指南 - 全流程解析"
  subtitle = "法国人才护照：从申请到公司注册的详细步骤和技巧"
  mainSections = ["post", "posts"]
  logo = "img/france-logo.png" # Expecting square dimensions
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2024"
  commit = false
  rss = true
  comments = true
  readingTime = true
  wordCount = true
  useHLJS = true
  socialShare = true
  delayDisqus = true
  showRelatedPosts = true
  ogTitle = "法国人才护照 - 全流程指南"
  ogDescription = "了解法国人才护照的详细申请流程，从签证申请到公司运营的每一步指南。"
  ogImage = "img/og-image.jpg"
  twitterCard = "summary_large_image"
  twitterTitle = "法国人才护照指南"
  twitterDescription = "法国人才护照全流程解析，帮助您轻松获取签证并顺利开展在法国的事业。"
  twitterImage = "img/twitter-card.jpg"
  metaDescription = "法国人才护照指南，涵盖从申请签证到公司注册的详细信息，帮助您顺利开启在法国的事业。"
  metaKeywords = "法国人才护照, 法国精英护照, 人才签证, 法国创业, 法国公司注册"

[Params.author]
  name = "TalentPass"
  website = "https://francetalentpass.com"
  email = "info@wishfactory.io"
  linkedin = "https://linkedin.com/company/talentpass"
  medium = "talentpass"
  discord = "https://discord.gg/XXXXXXX"

[languages]
  [languages.en]
    contentDir = "content/en" # English
    weight = 1
    languageName = "English" # Name shown in the main menu
    [languages.en.params]
      #linkedin = "https://muscaestar.github.io/myBlog/en/"
      title = "France Talent Passport - Complete Process Guide"
      subtitle = "A detailed guide on the France Talent Passport from visa to business operations."
      metaDescription = "Comprehensive guide for France Talent Passport, covering every step from visa application to business setup in France."
      metaKeywords = "France Talent Passport, French Talent Visa, Business in France, Company Setup in France, Startup in France"

    [[languages.en.menu.main]]
        name = "Guide"
        url = "page/guide/"
        weight = 1
    [[languages.en.menu.main]]
        name = "About"
        url = "page/about/"
        weight = 3
    [[languages.en.menu.main]]
        name = "Tags"
        url = "tags"
        weight = 3
  
  [languages.zh-CN]
    contentDir = "content/zh-CN" # Simplified Chinese
    weight = 2
    languageName = "简体中文" # Name shown in the main menu
    [languages.zh-CN.params]
      #linkedin = "https://muscaestar.github.io/myBlog/zh-CN/"
      title = "法国人才护照指南"
      subtitle = "法国人才护照指南是为了吸引全球人才而推出的政策，提供便捷的签证和公司注册流程。"
      metaDescription = "法国人才护照详细指南，帮助您从签证申请到公司注册的全流程操作。"
      metaKeywords = "法国人才护照, 法国精英护照, 人才签证, 法国创业, 法国公司注册"

    [[languages.zh-CN.menu.main]]
        name = "指南"
        url = "page/guide/"
        weight = 1
    [[languages.zh-CN.menu.main]]
        name = "关于"
        url = "page/about/"
        weight = 3
    [[languages.zh-CN.menu.main]]
        name = "标签"
        url = "tags"
        weight = 3